services:
  - type: web
    name: simplymoney-backend
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.simplymoney.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: simplymoney-backend.onrender.com
      - key: DATABASE_URL
        sync: false  # dodamy ręcznie po stworzeniu bazy w Neon
