# Generated by Django 5.1.7 on 2025-04-24 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('private', 'Private'), ('company', 'Company')], max_length=20)),
                ('category', models.CharField(choices=[('meat', 'Meat'), ('dairy', 'Dairy'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('preserves', 'Preserves'), ('jars', 'Jars'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('show_email', models.BooleanField(default=False)),
                ('show_phone', models.BooleanField(default=False)),
                ('exchange_type', models.CharField(choices=[('sale', 'For Sale'), ('trade', 'For Trade'), ('both', 'Sale or Trade')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
