# Generated by Django 5.1.7 on 2025-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
