# Generated by Django 5.1.7 on 2025-05-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcementimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnnouncementImages',
            new_name='AnnouncementImage',
        ),
    ]
