# Generated by Django 5.1.7 on 2025-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='label',
            field=models.CharField(default='swarm', max_length=40),
            preserve_default=False,
        ),
    ]
