# Generated by Django 5.1.7 on 2025-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_waitlistentry_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
